version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.10
    - 7.13.15
    - 7.13.16
    - 7.13.8
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.24.2
    - 5.26.3
    - 5.34.0
    - 5.35.0
  - dependency-name: core-js
    versions:
    - 3.10.2
    - 3.11.0
    - 3.8.2
    - 3.8.3
    - 3.9.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.10
    - 7.13.15
    - 7.13.8
  - dependency-name: sass
    versions:
    - 1.32.0
    - 1.32.11
    - 1.32.5
    - 1.32.8
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: testcafe
    versions:
    - 1.10.1
    - 1.11.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: ini
    versions:
    - 1.3.8
